FROM quay.io/centos/centos:stream9 AS builder

ARG K8SREPO=https://github.com/openshift/kubernetes.git
ARG K8SPR=2128
ARG K8SBRANCH=kubelet-llc

ENV HOME=/home/ci

RUN dnf --setopt=install_weak_deps=False -y install \
    golang-bin \
    systemd \
    rsync \
    gcc \
    git \
    make \
    gettext \
    which \
    findutils \
    bsdtar \
    createrepo_c \
    rpm-build \
    krb5-devel \
    git-core \
    && dnf clean all

WORKDIR /go/src/k8s.io
RUN git clone $K8SREPO

WORKDIR /go/src/k8s.io/kubernetes
RUN git fetch origin pull/$K8SPR/head:$K8SBRANCH
RUN git checkout $K8SBRANCH
RUN ./openshift-hack/build-rpms.sh

#
# Replace with the RHCOS base image url found this way
# Either use:
#   oc adm release info --image-for=rhel-coreos 4.16.ZZ
# Or as a developer do:
# 1. Go to https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable and click on the wanted OCP release
# 2. Wait for the changelog to load at the bottom of the page
# 3. find Changes from / Changes / Components / Red Hat Enterprise Linux CoreOS upgraded from (A) to (B)
# 4. Click (B) which will take you to the RHCOS release details page
# 5. Copy the RHCOS Base OS url to the FROM below
#
FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:da4c28471c05718a1e90879d5d932a9054a0e2e4248255bb079c58a3c13e58fe
COPY --from=builder /go/src/k8s.io/kubernetes/_output/local/releases/rpms/*.rpm /root/rpms/
RUN rpm-ostree override replace /root/rpms/*.rpm && \
    rpm-ostree cleanup -m && \
    ostree container commit

